name: Build OpenChests

on:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  build:
    name: Build Mod
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        id: build
        with:
          # This tells the action to package the .geode file for you
          combine: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenChests-Package
          # This uses the output from the build step to find your file
          path: ${{ steps.build.outputs.build-output }}
