name: Build OpenChests

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  geode:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: ubuntu-latest # Using Ubuntu to build as requested
            target: win

    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        id: build
        with:
          combine: true
          export-pdb: true
          build-config: ${{ env.BUILD_TYPE }}
          platform: win

  package-geode:
    name: Package Mod
    runs-on: ubuntu-latest
    needs: ['geode']

    steps:
      # This step grabs the built files from the previous job
      - uses: geode-sdk/build-geode-mod/combine@main
        id: build

      # This gives you the actual download link
      - uses: actions/upload-artifact@v4
        with:
          name: OpenChests-Geode
          path: ${{ steps.build.outputs.build-output }}
