name: Build OpenChests

on:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  build:
    name: Build Mod
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Geode Mod
        uses: geode-sdk/build-geode-mod@main
        id: build
        with:
          # This automatically downloads the SDK and 2.2081 headers
          combine: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenChests-Package
          # This grabs the actual .geode file created in the step above
          path: ${{ steps.build.outputs.build-output }}
